### ISSUE TITLE
Bug roguelike 1.7.10

### ISSUE THREAD

**Issue by Xen1290** [Greymerk/minecraft-roguelike#10]
http://pastebin.com/XGwsW6H5

This with I create a new world. World bugged.

**Comment by keenerb** [comment]
This still happens.

```
[B#301]  Time: 5/17/15 7:29 PM
[B#301]  Description: Exception while updating neighbours
[B#301]  
[B#301]  java.lang.NullPointerException: Exception while updating neighbours
[B#301]  	at net.minecraft.world.WorldServer.func_147477_a(WorldServer.java:404)
[B#301]  	at net.minecraft.block.BlockRedstoneComparator.func_149897_b(BlockRedstoneComparator.java:151)
[B#301]  	at net.minecraft.block.BlockRedstoneDiode.func_149695_a(SourceFile:136)
[B#301]  	at net.minecraft.world.World.func_147460_e(World.java:697)
[B#301]  	at net.minecraft.world.World.func_147459_d(World.java:649)
[B#301]  	at net.minecraft.block.BlockRedstoneWire.func_150172_m(BlockRedstoneWire.java:179)
[B#301]  	at net.minecraft.block.BlockRedstoneWire.func_149726_b(BlockRedstoneWire.java:199)
[B#301]  	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:655)
[B#301]  	at net.minecraft.world.World.func_147465_d(World.java:451)
[B#301]  	at greymerk.roguelike.worldgen.WorldGenPrimitive.setBlock(WorldGenPrimitive.java:29)
[B#301]  	at greymerk.roguelike.worldgen.WorldGenPrimitive.setBlock(WorldGenPrimitive.java:35)
[B#301]  	at greymerk.roguelike.worldgen.WorldGenPrimitive.setBlock(WorldGenPrimitive.java:39)
[B#301]  	at greymerk.roguelike.catacomb.dungeon.room.DungeonFirework.launcher(DungeonFirework.java:168)
[B#301]  	at greymerk.roguelike.catacomb.dungeon.room.DungeonFirework.generate(DungeonFirework.java:66)
[B#301]  	at greymerk.roguelike.catacomb.dungeon.SecretRoom.genRoom(SecretRoom.java:59)
[B#301]  	at greymerk.roguelike.catacomb.dungeon.SecretFactory.genRoom(SecretFactory.java:85)
[B#301]  	at greymerk.roguelike.catacomb.segment.part.SegmentDoor.genWall(SegmentDoor.java:40)
[B#301]  	at greymerk.roguelike.catacomb.segment.part.SegmentBase.generate(SegmentBase.java:22)
[B#301]  	at greymerk.roguelike.catacomb.segment.SegmentGenerator.genSegment(SegmentGenerator.java:64)
[B#301]  	at greymerk.roguelike.catacomb.CatacombTunneler.addSegments(CatacombTunneler.java:141)
[B#301]  	at greymerk.roguelike.catacomb.CatacombNode.segments(CatacombNode.java:115)
[B#301]  	at greymerk.roguelike.catacomb.CatacombLevel.generate(CatacombLevel.java:104)
[B#301]  	at greymerk.roguelike.catacomb.Catacomb.generate(Catacomb.java:73)
[B#301]  	at greymerk.roguelike.catacomb.Catacomb.generateNear(Catacomb.java:44)
[B#301]  	at greymerk.roguelike.catacomb.Catacomb.spawnInChunk(Catacomb.java:133)
[B#301]  	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:13)
[B#301]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106)
[B#301]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
[B#301]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
[B#301]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
[B#301]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[B#301]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[B#301]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[B#301]  	at net.minecraft.world.World.func_72964_e(World.java:419)
[B#301]  	at net.minecraft.world.World.func_147439_a(World.java:345)
[B#301]  	at shukaro.artifice.util.BlockCoord.getBlock(BlockCoord.java:368)
[B#301]  	at shukaro.artifice.world.WorldGenSulfur.canGenHere(WorldGenSulfur.java:103)
[B#301]  	at shukaro.artifice.world.WorldGenSulfur.generateFeature(WorldGenSulfur.java:76)
[B#301]  	at cofh.core.world.WorldHandler.generateWorld(WorldHandler.java:242)
[B#301]  	at cofh.core.world.WorldHandler.generate(WorldHandler.java:205)
[B#301]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106)
[B#301]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
[B#301]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
[B#301]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
[B#301]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[B#301]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[B#301]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[B#301]  	at net.minecraft.world.World.func_72964_e(World.java:419)
[B#301]  	at net.minecraft.world.World.func_147439_a(World.java:345)
[B#301]  	at net.minecraft.world.World.func_147437_c(World.java:365)
[B#301]  	at biomesoplenty.common.world.WorldProviderSurfaceBOP.getTopBlockCoord(WorldProviderSurfaceBOP.java:42)
[B#301]  	at biomesoplenty.common.world.WorldProviderSurfaceBOP.func_76566_a(WorldProviderSurfaceBOP.java:14)
[B#301]  	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
[B#301]  	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
[B#301]  	at net.minecraft.world.World.<init>(World.java:260)
[B#301]  	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
[B#301]  	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
[B#301]  	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
[B#301]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[B#301]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[B#301]  
```

**Comment by Greymerk** [comment]
This has been patched by wrapping the call in a try/catch. Best I can do, should prevent the error from causing the server crash.

**Comment by katzenpapst** [comment]
Could you make a build with this fix for 1.7.10, too? Or, at least, is there an option to disable the firework room generation?

**Comment by Greymerk** [comment]
Sure, I had forgotten this was after the last time I posted a 1.7 build. It's getting complicated juggling all these minecraft versions.

**Comment by katzenpapst** [comment]
Meanwhile, I tried cloning the repo, adding the try-catch myself and rebuilding the mod. That didn't work, apparently because nullpointerexception are somehow special? In the end, I just commented out the firework room, and I'm playing that right now...
