### ISSUE TITLE
Random Crash while playing

### ISSUE THREAD

**Issue by winsrp** [Greymerk/minecraft-roguelike#128]
while playing and moving around this stops the server.

Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at greymerk.roguelike.dungeon.settings.SpawnCriteria.isValid(SpawnCriteria.java:80)
	at greymerk.roguelike.dungeon.settings.DungeonSettings.isValid(DungeonSettings.java:166)
	at greymerk.roguelike.dungeon.settings.SettingsResolver.getBuiltin(SettingsResolver.java:85)
	at greymerk.roguelike.dungeon.settings.SettingsResolver.getSettings(SettingsResolver.java:24)
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:108)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:194)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:172)

**Comment by ElectricBlue1** [comment]
Same issue,

Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at greymerk.roguelike.dungeon.settings.SpawnCriteria.isValid(SpawnCriteria.java:80)
	at greymerk.roguelike.dungeon.settings.DungeonSettings.isValid(DungeonSettings.java:166)
	at greymerk.roguelike.dungeon.settings.SettingsResolver.getBuiltin(SettingsResolver.java:85)
	at greymerk.roguelike.dungeon.settings.SettingsResolver.getSettings(SettingsResolver.java:24)
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:108)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:194)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1015)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:976)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at greymerk.roguelike.dungeon.settings.SpawnCriteria.isValid(SpawnCriteria.java:80)
	at greymerk.roguelike.dungeon.settings.DungeonSettings.isValid(DungeonSettings.java:166)
	at greymerk.roguelike.dungeon.settings.SettingsResolver.getBuiltin(SettingsResolver.java:85)
	at greymerk.roguelike.dungeon.settings.SettingsResolver.getSettings(SettingsResolver.java:24)
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:108)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:194)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1015)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:976)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)

-- Affected level --
Details:
	Level name: world
	All players: 3 total; [EntityPlayerMP['Panda413'/502, l='world', x=1873.67, y=67.00, z=329.41], EntityPlayerMP['SrDestino'/36479, l='world', x=1880.16, y=72.00, z=327.19], EntityPlayerMP['DaggerTM'/62441, l='world', x=-716.24, y=76.43, z=-684.05]]
	Chunk stats: ServerChunkCache: 1176 Drop: 0
	Level seed: 4306299744598883094
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (232,64,252), Chunk: (at 8,4,12 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8118115 game time, 39901642813 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 6459 (now: false), thunder time: 69600 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

**Comment by svenhjol** [comment]
See commit above for info.  I've built a version of 1.12-1.7.0 with a bypass of the biome check that is causing a problem server-side only, and attached it to this comment.  Not ideal but I really like this mod and want to play it before a proper fix gets implemented :)

[RoguelikeDungeons-1.12-1.7.0-svenhjol.jar.zip](https://github.com/Greymerk/minecraft-roguelike/files/1166436/RoguelikeDungeons-1.12-1.7.0-svenhjol.jar.zip)

**Comment by twoworlds** [comment]
I can confirm the crash, @svenhjol s solutions seems to work on my server

**Comment by Greymerk** [comment]
I've also fixed it in the latest build. Will upload it to curse when i'm able. They're having some sort of outtage at the moment.

I've noticed a number of other mods have had a similar issue with this particular method. It winds up being a simple workaround.

**Comment by DrGirlfriend** [comment]
Will there also be a fix for 1.11.2?
