### ISSUE TITLE
[1.12.1] Server Crashes if stronghold gen set to false, even if dim blacklisted in roguelike cfg

### ISSUE THREAD

**Issue by xkobalx** [Greymerk/minecraft-roguelike#132]
Creating a world, or dimension using the native custom world options and setting strongholds to false  causes a crash even if the dimension is blacklisted in the roguelike dungeons config file.

Crash will not occur until a player enters that dimension/world

Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:141)
	at net.minecraft.world.gen.structure.MapGenStronghold.func_180706_b(MapGenStronghold.java:77)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_180513_a(ChunkGeneratorOverworld.java:569)
	at net.minecraft.world.gen.ChunkProviderServer.func_180513_a(ChunkProviderServer.java:307)
	at greymerk.roguelike.worldgen.WorldEditor.findNearestStructure(WorldEditor.java:205)
	at greymerk.roguelike.dungeon.Dungeon.validLocation(Dungeon.java:223)
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:103)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:194)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1015)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:995)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)

**Comment by Greymerk** [comment]
patched this for the 1.12.2 update.
