### ISSUE TITLE
Redstone Bug Crashes Servers

### ISSUE THREAD

**Issue by Da-Spud** [Greymerk/minecraft-roguelike#196]
Basically whenever a player is inside or near to a RL dungeon, the server console is spammed with messages about redstonewireblock or something similar, causing lag, then once the server's tick takes longer than 60.00seconds, the server will time out

This is the crash report that is then created:

Time: 9/22/19 9:23 AM
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at java.io.PrintStream.write(PrintStream.java:480)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
	at java.io.PrintStream.write(PrintStream.java:527)
	at java.io.PrintStream.print(PrintStream.java:683)
	at net.minecraftforge.server.terminalconsole.TerminalConsoleAppender.append(TerminalConsoleAppender.java:320)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960)
	at org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:1629)
	at org.spongepowered.asm.util.PrettyPrinter.logString(PrettyPrinter.java:1129)
	at org.spongepowered.asm.util.PrettyPrinter.log(PrettyPrinter.java:1116)
	at org.spongepowered.asm.util.PrettyPrinter.trace(PrettyPrinter.java:1048)
	at org.spongepowered.common.event.tracking.PhaseTracker.printMessageWithCaughtException(PhaseTracker.java:513)
	at org.spongepowered.common.event.tracking.PhaseTracker.checkMaxBlockProcessingDepth(PhaseTracker.java:1167)
	at org.spongepowered.common.event.tracking.PhaseTracker.notifyBlockOfStateChange(PhaseTracker.java:708)
	at net.minecraft.world.WorldServer.throwNotifyNeighborAndCall(WorldServer.java:3113)
	at net.minecraft.world.WorldServer.func_175685_c(WorldServer.java:3086)
	at net.minecraft.block.BlockRedstoneWire.func_176338_e(BlockRedstoneWire.java:159)
	at net.minecraft.block.BlockRedstoneWire.func_189540_a(BlockRedstoneWire.java:341)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at org.spongepowered.common.event.tracking.PhaseTracker.notifyBlockOfStateChange(PhaseTracker.java:713)
	at net.minecraft.world.WorldServer.throwNotifyNeighborAndCall(WorldServer.java:3113)
	at net.minecraft.world.WorldServer.func_175685_c(WorldServer.java:3086)

and would spam the same text throughout the report.

**Comment by Da-Spud** [comment]
Full Crash Report:

[crash-2019-09-22_09.23.01-server.txt](https://github.com/Greymerk/minecraft-roguelike/files/3639960/crash-2019-09-22_09.23.01-server.txt)
