### ISSUE TITLE
update to 1.21.4

### ISSUE THREAD

**Issue by wh0oo** [Greymerk/minecraft-roguelike#241]
Just putting this out here into the universe.  I attempted to use the latest release (1.21.3) and server hard crashed.  Not sharing the crash report unless asked, since it was for another version.

Thanks!!  This is an awesome structure!

**Comment by wh0oo** [comment]
I looked at the crash log, its a pretty easy share,

````
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2024-12-06 23:50:39
Description: Exception ticking world

java.lang.NoSuchMethodError: 'void net.minecraft.class_2573.method_10913(net.minecraft.class_1799, net.minecraft.class_1767)'
        at knot//com.greymerk.roguelike.editor.blocks.WallBanner.generate(WallBanner.java:33)
        at knot//com.greymerk.roguelike.editor.blocks.WallBanner.generate(WallBanner.java:20)
        at knot//com.greymerk.roguelike.dungeon.fragment.wall.WallBannerFragment.generate(WallBannerFragment.java:18)
        at knot//com.greymerk.roguelike.dungeon.room.Corridor.decorations(Corridor.java:60)
        at knot//com.greymerk.roguelike.dungeon.room.Corridor.generate(Corridor.java:29)
        at knot//com.greymerk.roguelike.events.WorldTickGenerateRooms.onStartTick(WorldTickGenerateRooms.java:28)
        at knot//net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:66)
        at knot//net.minecraft.class_3218.handler$bcl000$fabric-lifecycle-events-v1$startWorldTick(class_3218.java:4837)
        at knot//net.minecraft.class_3218.method_18765(class_3218.java:309)
        at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
        at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
        at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
        at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
        at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at knot//com.greymerk.roguelike.editor.blocks.WallBanner.generate(WallBanner.java:33)
        at knot//com.greymerk.roguelike.editor.blocks.WallBanner.generate(WallBanner.java:20)
        at knot//com.greymerk.roguelike.dungeon.fragment.wall.WallBannerFragment.generate(WallBannerFragment.java:18)
        at knot//com.greymerk.roguelike.dungeon.room.Corridor.decorations(Corridor.java:60)
        at knot//com.greymerk.roguelike.dungeon.room.Corridor.generate(Corridor.java:29)
        at knot//com.greymerk.roguelike.events.WorldTickGenerateRooms.onStartTick(WorldTickGenerateRooms.java:28)
        at knot//net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:66)
        at knot//net.minecraft.class_3218.handler$bcl000$fabric-lifecycle-events-v1$startWorldTick(class_3218.java:4837)

-- Affected level --

````
