### ISSUE TITLE
crash using realistic terrain generator

### ISSUE THREAD

**Issue by Jiraiyah** [Greymerk/minecraft-roguelike#49]
i get an NPE from your mod when i try to generate new world with RTG mod : 

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraftforge.common.BiomeDictionary.getTypesForBiome(BiomeDictionary.java:206)
	at greymerk.roguelike.dungeon.Dungeon.validLocation(Dungeon.java:154)
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:59)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:138)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:113)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:997)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:979)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:175)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:96)
	at net.minecraft.world.World.func_72964_e(World.java:294)
	at net.minecraft.world.World.func_175726_f(World.java:289)
	at jiraiyah.villageinfo.events.WorldDataCollector.getSpawnChunks(WorldDataCollector.java:83)
	at jiraiyah.villageinfo.events.WorldDataCollector.worldLoadEvent(WorldDataCollector.java:70)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_74_WorldDataCollector_worldLoadEvent_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:95)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:119)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Greymerk** [comment]
Strange... it's getting a null value back when it asks what the biome at that location is. lovely.

**Comment by RealGrep** [comment]
I can tell you I had the exact same issue, running RTG (with Biomes of Plenty) in 1.9. Forge version 1865.

**Comment by Jiraiyah** [comment]
I opened the same issue in RTG's repo, may help if you guys talk with him there : 

https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues/78

**Comment by VelocityRa** [comment]
Could you try generating a world without structures? It's an option in the menu where you choose the Realistic world type.

**Comment by Jiraiyah** [comment]
it still gives the NPE

**Comment by VelocityRa** [comment]
Alright, thanks for testing.

**Comment by Jiraiyah** [comment]
no problem, anything i can do i won't waist a single minute to do :D

**Comment by Greymerk** [comment]
Appears to be an issue with RTG's biome provider. They plan to investigate the issue during their 1.9 rewrite.
