### ISSUE TITLE
unknown method call #isBiomeOfType on BiomeDictionary

### ISSUE THREAD

**Issue by TheGriz** [Greymerk/minecraft-roguelike#73]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.11-1.2.0.0.b79.jar)
  CXLibraryCore (cxlibrary-1.11-1.3.0.jar)
  CorePlugin (FluxedRedstone-2.6.0.54.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.jar)
  RBLoadingPlugin (RealBench-1.11-1.3.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.0.1.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 12/2/16 4:12 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.common.BiomeDictionary.isBiomeOfType(Lnet/minecraft/world/biome/Biome;Lnet/minecraftforge/common/BiomeDictionary$Type;)Z
	at greymerk.roguelike.dungeon.Dungeon.validLocation(Dungeon.java:171)
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:60)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:145)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:122)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:174)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1182233608 bytes (1127 MB) / 3002490880 bytes (2863 MB) up to 8482586624 bytes (8089 MB)
	JVM Flags: 5 total; -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.35 Powered by Forge 13.19.0.2176 Optifine OptiFine_1.11_HD_U_B1 119 mods loaded, 119 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	UCHIJAA	roguelike{1.6.0} [Roguelike Dungeons] (RoguelikeDungeons-1.11-1.6.0.jar)

**Comment by abramsba** [comment]
Same error on Windows and Ubuntu with fresh Forge install

**Comment by TheGriz** [comment]
Same error with OS X and fresh Forge v13.19.0.2178 and MC v1.11 install. No other mods.

**Comment by Greymerk** [comment]
Something has indeed changed in forge itself. It's early in the lifecycle of 1.11 so i'm not surprised. Will fix this asap.

**Comment by TheGriz** [comment]
Thoroughly enjoy you mod. I play survival mode and this mod adds a good balance of risk/reward as you progress down level by level. Big fan of Rougue-like games in general +1

**Comment by spoopyghostramses** [comment]
Getting the same error, thanks for looking into it! Love your mod.

**Comment by Greymerk** [comment]
Fixt. Uploaded 1.6.1 to curseforge, pending approval. Should be up shortly.
