### ISSUE TITLE
Crash in single player

### ISSUE THREAD

**Issue by LemADEC** [Greymerk/minecraft-roguelike#99]
Crash with RoguelikeDungeons-1.10.2-1.5.7.jar while exploring the world in single player
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.344.jar)
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  ForgelinPlugin (Forgelin-1.3.1.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 3/5/17 5:17 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:102)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:185)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:102)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:185)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['LemADEC'/549, l='New World', x=-305.25, y=79.24, z=188.48]]
	Chunk stats: ServerChunkCache: 885 Drop: 0
	Level seed: -5302833872968576651
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (160,64,-180), Chunk: (at 0,4,12 in 10,-12; contains blocks 160,0,-192 to 175,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 11090 game time, 11090 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 58386 (now: false), thunder time: 41381 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 550810736 bytes (525 MB) / 3398434816 bytes (3241 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2239 78 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2239.jar) 
	UCHIJAAAA	Forge{12.18.3.2239} [Minecraft Forge] (forge-1.10.2-12.18.3.2239.jar) 
	UCHIJAAAA	JEI{3.14.7.415} [Just Enough Items] (jei_1.10.2-3.14.7.415.jar) 
	UCHIJAAAA	abyssalcraft{1.9.3.10} [AbyssalCraft] (AbyssalCraft-1.10.2-1.9.3.10.jar) 
	UCHIJAAAA	aether_legacy{v1.3.1-1.10.2} [Aether Legacy] (aether_legacy-1.3.1.jar) 
	UCHIJAAAA	arsmagica2{1.5.017} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHIJAAAA	baublesstuff{3.0.2} [Baubles Stuff] (baublesstuff-3.0.2.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCHIJAAAA	BloodMagic{1.10.2-2.1.5-74} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.5-74.jar) 
	UCHIJAAAA	BloodArsenal{1.10.2-2.0.1-17} [Blood Arsenal] (BloodArsenal-1.10.2-2.0.1-17.jar) 
	UCHIJAAAA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.10.2-1.5.1.jar) 
	UCHIJAAAA	bookshelf{1.4.4.344} [Bookshelf] (Bookshelf-1.10.2-1.4.4.344.jar) 
	UCHIJAAAA	Botania{r1.9-340} [Botania] (Botania r1.9-340.jar) 
	UCHIJAAAA	chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.1-1.10.2.jar) 
	UCHIJAAAA	coroutil{1.10.2-1.1.13} [CoroUtil Library] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.13.jar) 
	UCHIJAAAA	crossroads{1.10.2-1.3.7} [Crossroads] (crossroads-1.10.2-1.3.7.jar) 
	UCHIJAAAA	cyclopscore{0.9.2} [Cyclops Core] (CyclopsCore-1.9.4-0.9.2.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	dldungeonsjdg{1.9.0} [Doomlike Dungeons] (DoomlikeDungeons-1.9.0-MC1.10.jar) 
	UCHIJAAAA	druidry{2016.9.26-1.9.4} [§2Druidry] (druidry(2016.9.26)(1.9.4).jar) 
	UCHIJAAAA	embers{0.104} [Embers] (embers-0.104.jar) 
	UCHIJAAAA	eplus{4.1.0.116} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.116.jar) 
	UCHIJAAAA	evilcraft{0.10.20} [EvilCraft] (EvilCraft-1.10.2-0.10.20.jar) 
	UCHIJAAAA	fe{1.3} [Food Expansion] (FoodExpansion1.3.1-1.10.2.jar) 
	UCHIJAAAA	forgelin{1.3.0} [Forgelin] (Forgelin-1.3.1.jar) 
	UCHIJAAAA	grimoireofgaia{1.5.3} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.10.2-1.5.3.jar) 
	UCHIJAAAA	hardcorewither{2.2.3} [Hardcore Wither] (hardcoreWither-1.10.2-2.2.3-beta-4bd2a01-universal.jar) 
	UCHIJAAAA	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UCHIJAAAA	justenoughbuttons{1.10.2-1.7.1} [Just Enough Buttons] (justenoughbuttons-1.10.2-1.7.1.jar) 
	UCHIJAAAA	justenoughdimensions{1.3.5} [Just Enough Dimensions] (justenoughdimensions-1.10.2-1.3.5.jar) 
	UCHIJAAAA	jeresources{0.5.9.3} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.9.3.jar) 
	UCHIJAAAA	levels{r1.2.4} [Levels] (Levels 2-1.10.2-r1.2.4.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.12.8-1.10.2.jar) 
	UCHIJAAAA	librarianlib{1.10.1} [LibrarianLib] (librarianlib-1.10.1.jar) 
	UCHIJAAAA	lycanitesmobs{1.15.1.5 - MC 1.10.2} [Lycanites Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	arcticmobs{1.15.1.5 - MC 1.10.2} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	demonmobs{1.15.1.5 - MC 1.10.2} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	desertmobs{1.15.1.5 - MC 1.10.2} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	forestmobs{1.15.1.5 - MC 1.10.2} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	freshwatermobs{1.15.1.5 - MC 1.10.2} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	infernomobs{1.15.1.5 - MC 1.10.2} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	junglemobs{1.15.1.5 - MC 1.10.2} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	mountainmobs{1.15.1.5 - MC 1.10.2} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	plainsmobs{1.15.1.5 - MC 1.10.2} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	saltwatermobs{1.15.1.5 - MC 1.10.2} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	shadowmobs{1.15.1.5 - MC 1.10.2} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	swampmobs{1.15.1.5 - MC 1.10.2} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.15.1.5 [1.10.2].jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	mobtotems{1.10.2-0.1.2} [Mob Totems] (mobtotems-1.10.2-0.1.2.jar) 
	UCHIJAAAA	mysticalagriculture{1.4.3} [Mystical Agriculture] (mysticalagriculture[1.10.2]-1.4.3.jar) 
	UCHIJAAAA	botanicaladdons{1.10} [Natural Pledge] (NaturalPledge-r1.10.jar) 
	UCHIJAAAA	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
	UCHIJAAAA	overlord{2.1.1} [Overlord] (Overlord-1.10.2-2.1.1.jar) 
	UCHIJAAAA	pearcelmod{1.10.2-2.3.0} [Pearcel Mod] (pearcelmod-1.10.2-2.3.0.jar) 
	UCHIJAAAA	ProjectE{1.10.2-PE1.2.0} [ProjectE] (ProjectE-1.10.2-PE1.2.0.jar) 
	UCHIJAAAA	psionup{15.1} [PSIonic Upgrades] (PSIonicUpgrades-r1.15.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.639} [Reliquary] (Reliquary-1.10.2-1.3.3.639.jar) 
	UCHIJAAAA	roguelike{1.5.7} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.7.jar) 
	UCHIJAAAA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJAAAA	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	UCHIJAAAA	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	UCHIJAAAA	tammodized{0.6.2} [TamModized] (TamModized-1.10.2-0.6.2.jar) 
	UCHIJAAAA	totemic{1.10.2-0.8.1} [Totemic] (Totemic-1.10.2-0.8.1.jar) 
	UCHIJAAAA	vampirism{1.1.0-alpha+02-23-15-57} [Vampirism] (Vampirism-1.10.2-1.1.0-alpha+02-23-15-57.jar) 
	UCHIJAAAA	teamlapen-lib{1.1.0-alpha+02-23-15-57} [TeamLapen Library] (Vampirism-1.10.2-1.1.0-alpha+02-23-15-57.jar) 
	UCHIJAAAA	vitality{2.4} [Vitality] (vitality-2.4.jar) 
	UCHIJAAAA	voidcraft{0.16.1} [VoidCraft] (VoidCraft-1.10.2-0.16.1.jar) 
	UCHIJAAAA	wearablebackpacks{1.6.0} [Wearable Backpacks] (WearableBackpacks-1.10.2-1.6.0.jar) 
	UCHIJAAAA	zombieawareness{1.10.2-1.11.6} [Zombie Awareness] (zombieawareness-1.10.2-1.11.6.jar) 
	UCHIJAAAA	librarianliblate{1.10.1} [LibrarianLib Stage 2] (librarianlib-1.10.1.jar) 
	Loaded coremods (and transformers): 
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.344.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  am2.asm.Transformer
ForgelinPlugin (Forgelin-1.3.1.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['LemADEC'/549, l='New World', x=-305.25, y=79.24, z=188.48]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge
```

**Comment by Greymerk** [comment]
I did some checking and at first glance I don't why this would be happening. Will investigate further later.
